### ISSUE TITLE
Pest parser does not handle significant whitespaces correctly

### ISSUE THREAD

**Issue by Sytten** [async-graphql/async-graphql#1039]
**EDIT:** I kinda opened a larger can or worms, please read all comments to understand the full issue

## Expected Behavior
Given a query like:
```graphql
fragment onboardingFull on OnboardingState {
  license
}

query globalConfig {
  globalConfig {
    onboarding {
      ...onboardingFull
    }
  }
}

```

It used to work before to update from 4.0.1 to 4.0.10. But it now interprets the "on" in the fragment name. 

## Actual Behavior

Parsing error:
```
 --> 9:5
  |
9 |     }
  |     ^---
  |
  = expected selection_set or directive
```

## Steps to Reproduce the Problem

1. Create a fragment where the name starts with "on"
2. Send it to the server
3. See failure

## Specifications

- Version: 4.0.10
- Platform: All
- Subsystem: All

**Comment by Sytten** [comment]
I believe the issue is this change in the parser: https://github.com/async-graphql/async-graphql/commit/1f67e3adcdfd56f651ec6d3e540ad5b6a431f700#diff-7fe48281e06de04d34f56adf27094658fcfd043c278255b994be6a9357409231R19

Because the whitespace are [ignored](https://stackoverflow.com/questions/63301235/using-pest-rs-how-can-i-allow-non-significant-whitespace-after-a-keyword) with https://github.com/async-graphql/async-graphql/blob/69dfe255d0b4821822c5f8a76bd2c0305f8d71f4/parser/src/graphql.pest#L1

It thinks the fragment spread is using a type_condition https://github.com/async-graphql/async-graphql/blob/69dfe255d0b4821822c5f8a76bd2c0305f8d71f4/parser/src/graphql.pest#L23

I believe we can fix the issue by setting `type_condition = { "on " ~ name }` to tell pest that the space after on is significant. Maybe there is another way though so feel free to fix it as you like.

**Comment by Sytten** [comment]
Further reading of the current pest grammer indicates that a lot of significant whitespaces are currently ignored and this is not good. For example `fragment_definition = { "fragment" ~ name ~ type_condition ~ directives? ~ selection_set }` makes it so that `fragmentmyfragmentonMyType` is valid while it is clearly not.

The problem is to fix that we would need to make rules atomic (with `${ }`) and all other rules not atomic (with `!{ }`). At least until pest 3 is released with https://github.com/pest-parser/pest/issues/271.

For fragment that would look like:
```pest
fragment_definition = @{ "fragment" ~ WHITESPACE+ ~ name ~ WHITESPACE+ ~ type_condition ~ WHITESPACE* ~ directives? ~ WHITESPACE* ~ selection_set }
type_condition = !{ "on " ~ name }
selection_set = !{ "{" ~ selection+ ~ "}" }
directives       = !{       directive+ }
```

I am unsure how you want to proceed with this significant vs non significant spacing issue @sunli829, but let me know.

**Comment by sunli829** [comment]
I fixed it in the master branch, please help to test it. 🙂

**Comment by Sytten** [comment]
Will do, I believe the rest is still broken though but I guess its all right.
