### ISSUE TITLE
Bug with query fragment

### ISSUE THREAD

**Issue by sync** [async-graphql/async-graphql#114]
### with the following query:

```
query roomQuery($roomId: String!) {
  room(id: $roomId) {
    account {
      name
      testAccount
      id
    }
    ...RoomJoinAttendeeCheckin_room
    id
  }
}
fragment RoomJoinAttendeeCheckin_room on Room {
  account {
    id
    timezone
    name
  }
}
```

### I am expected to get this back

```
{
  "data": {
    "room": {
      "account": {
        "id": "QWNjb3VudDo1NzE2ZmIzNGQ1MjViM2VhNGY0MjMwZjQ=",
        "timezone": "Australia/Melbourne",
        "name": "Blu Property Malverned",
        "testAccount": true
      },
      "id": "Um9vbTozMg=="
    }
  }
}
```

But instead i get this back

```
{
  "data": {
    "room": {
      "account": {
        "id": "QWNjb3VudDo1NzE2ZmIzNGQ1MjViM2VhNGY0MjMwZjQ=",
        "timezone": "Australia/Melbourne",
        "name": "Blu Property Malverned"
      },
      "id": "Um9vbTozMg=="
    }
  }
}
```

`testAccount` is missing

**Comment by sync** [comment]
### same issue with:

```
query roomQuery($roomId: String!) {
  room(id: $roomId) {
    ...RoomJoinAttendeeCheckinB_room
    ...RoomJoinAttendeeCheckin_room
    id
  }
}

fragment RoomJoinAttendeeCheckinB_room on Room {
  account {
    id
    timezone
    name
    testAccount
  }
}

fragment RoomJoinAttendeeCheckin_room on Room {
  account {
    id
    timezone
    name
  }
}
```

**Comment by sync** [comment]
Basically last fragment wins, for example this works:

```
query roomQuery($roomId: String!) {
  room(id: $roomId) {
    ...RoomJoinAttendeeCheckinB_room
    ...RoomJoinAttendeeCheckin_room
    id
  }
}

fragment RoomJoinAttendeeCheckinB_room on Room {
  account {
    id
    timezone
    name
  }
}

fragment RoomJoinAttendeeCheckin_room on Room {
  account {
    id
    timezone
    name
    testAccount
  }
}
```

**Comment by sunli829** [comment]
I am solving this bug. 😁

**Comment by sync** [comment]
amazing 💯

**Comment by sunli829** [comment]
I fixed this bug, please upgrade to `1.13.4`.

**Comment by sync** [comment]
can confirm it's working thank you

**Comment by kop** [comment]
The bug seems to be still there.

It does not appear for simple cases anymore, but it still appears for highly nested types.

Here is an example:

```graphql
query {
  account(id: "QWNjb3VudDsvYWNjb3VudHMvMTVmZjlkZDYtMzJhNi00MTdiLWIwMDQtNmY2OWQ3Y2M0Yzhi") {
    ...FragmentA
  }
}

fragment FragmentA on Account {
    databases(last: 1) {
      edges {
        node {
          ...FragmentB
          ...FragmentC
          bindings {
            edges {
              node {
                engine {
                  id
                }
              }
            }
          }
        }
      }
    }
}

fragment FragmentB on Database {
  bindings {
    edges {
      node {
        engine {
          currentStatus
        }
      }
    }
  }
}

fragment FragmentC on Database {
  bindings {
    edges {
      node {
        engine {
          desiredStatus
        }
      }
    }
  }
}
```

Returns:

```json
{
  "data": {
    "account": {
      "databases": {
        "edges": [
          {
            "node": {
              "bindings": {
                "edges": [
                  {
                    "node": {
                      "engine": {
                        "id": "RW5naW5lOy9hY2NvdW50cy8xNWZmOWRkNi0zMmE2LTQxN2ItYjAwNC02ZjY5ZDdjYzRjOGIvZW5naW5lcy8wMzdiZGI4OC00MTAzLTRkZDAtYWRkNi00NjliYzg2MzU3YjA="
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

I expected `id`, `currentStatus` and `desiredStatus` to be returned, but only `id` was returned.

**Comment by sunli829** [comment]
Can you provide a test case that can reproduce the problem? This way I can solve it faster. 🙂

**Comment by kop** [comment]
@sunli829 After more research, I think my bug is not the same as the one from this issue, so I created a new issue: https://github.com/async-graphql/async-graphql/issues/345
