### ISSUE TITLE
Bring back validator error extensions

### ISSUE THREAD

**Issue by cortopy** [async-graphql/async-graphql#1174]
## Description of the feature

I've been digging into past versions and it seems that there used to be trait called `InputValueValidator` that allowed to return an Error with extensions after this PR https://github.com/async-graphql/async-graphql/pull/564

This solved this request https://github.com/async-graphql/async-graphql/issues/385, which is exactly what I'm trying to achieve.

Without Error extensions, it's difficult for frontend clients to know what exactly is wrong, but the current trait of `CustomValidator` only allows to return a String in the `check` method.

Could the old behaviour be brought back? I don't see any removal notes from the CHANGELOG either

**Comment by sunli829** [comment]
Fixed in `master`, here is the example:

https://github.com/async-graphql/async-graphql/blob/c54591de71e5451df0e4befa8adebc7207a32038/tests/validators.rs#L582

**Comment by sunli829** [comment]
Released in `v5.0.4`

**Comment by cortopy** [comment]
Thanks so much @sunli829  for being this quick!!!

I've tested the new version and it's great but I still can't use custom Graphql errors.

For example:

```rust
#[derive(Debug, Error)]
pub enum GraphqlError {
    #[error("InternalServerError")]
    InternalServerError(String),
    #[error("Could not find resource")]
    NotFound,
    #[error("Unauthenticated")]
    Unauthenticated,
    #[error("Unable to complete GRPC")]
    GrpcFailure(Status),
    #[error("Invalid user input")]
    BadUserInput(HashMap<String, String>),
}

impl ErrorExtensions for GraphqlError {
    fn extend(&self) -> FieldError {
      ...
    }
}
```

I can't do this:

```rust
let fields = HashMap::new();
let error: InputValueError = GraphqlError::BadUserInput(fields).extend().into()
```

because `async_graphql::Error` doesn't implement `std::fmt::Display`
